### ISSUE TITLE
[OFFTOPIC] Idea for a libretro-powered computer/emulator

### ISSUE THREAD

**Issue by vico93** [Drathonix/LoadMyChunks#14]
_Well, i saw that you have interest in CC:T stuff, so i take liberty to suggest this here (i didnt find other way to contact you, sorry to post this on the issue tracker of LMC)._

What about code a mod that, basically, add a block, CC:Tweaked's computer-like, that instead of booting CC:T lua platform would boot to a libretro core or straight a "content" (eg.: ROM) provided by the player/server owner.

Cores and "content" would be provided via datapacks (since i envision it to be server-side controlled), and maybe add a rudimentary netplay feature (akin to how snes9x handles that, kinda crap but only for sake of completeness) to be able to play with other players in the same server.

PS.: image for illustration purposes only, just a mockup of how it would look like in-game:
![image](https://github.com/Drathonix/LoadMyChunks/assets/3485505/1774d289-a4aa-4678-91ec-1d4b994ae844)

If possible, this modified computer could interface with CC:T monitors and render the emulated screen on that.
![image](https://github.com/Drathonix/LoadMyChunks/assets/3485505/6481e2f3-cce4-468a-9271-038fc865c3bd)

About the technical aspect of the idea, i think its possible to run c++ stuff in java (via jni), maybe this could be of good use for this idea:
https://github.com/leiradel/lrcpp

What do you think?

**Comment by Drathonix** [comment]
1. I have a discord server https://discord.gg/sBRwWXmaXG
2. You'd be better off suggesting this idea to the actual CC:T devs.

This really isn't anything I'd be interesting in creating myself to be honest. Your suggestion requires mixining or forking CC:T which is not really a feasible idea. It'd be better just to make another computer mod. LoadMyChunks needs to mixin CC:T to ensure the chunkloading mechanism works correctly but that's about all it does.

I'm going to set a precedent in this repo: do not suggest things external to the purpose of this mod, if you want to do that, join the discord (I'll add the link to the read me and on curse, its already on modrinth)
