### ISSUE TITLE
Game crashes after updating to version 1.06

### ISSUE THREAD

**Issue by xardius** [Drathonix/LoadMyChunks#20]
**Mod Version**
LoadMyChunks-1.06-1.21

**What were you doing before the crash happened?**
Updating the Mod from 1.05hf2 to 1.06

The game crashes with exit code 1 right on start. I can't even get to the menu.

Going back to 1.05hf2 fixed the problem.

**Provide Logs here:**
https://pastebin.com/SeKHskKH

**Comment by Drathonix** [comment]
Ok this is very weird. In all previous versions, the refmap field was automatically added to the mixins when I built the jars, for whatever reason, this stopped happening in the 1.0.6 update. Literally nothing changed in the build script that could have caused this. I don't know why this feature randomly broke.

I'll just explicitly declare the mixin refmap from now on. Be on the look out for 1.0.6-hf1

**Comment by Drathonix** [comment]
Literally no idea what caused this. All mixin refmaps have been showing up in my testing right now. I don't know why it failed on the mass publish this one time. hf1 has been published and I have confirmed that the refmap is present in the file and is present in the mixins.json files.

Frustrating that the automation failed one time for seemingly no reason.
