### ISSUE TITLE
[Crash] Crash when Chunky is finishing pregeneration

### ISSUE THREAD

**Issue by vico93** [Drathonix/LoadMyChunks#22]
**Mod Version**
LoadMyChunks-1.0.6-hf1+1.21+fabric

**What were you doing before the crash happened?**
Basically, [Chunky](https://modrinth.com/plugin/chunky) ([GH](https://github.com/pop4959/Chunky)) was finishing a 2500x2500 pregeneration on singleplayer and was almost finished when this crash happened. Related to #21 ?

**Provide Logs here:**
[Gist](https://gist.github.com/vico93/caa4fd31f69bc5f4e2be33bca1a3a09a)

**Comment by Drathonix** [comment]
Yup. This is likely a threading issue as mentioned in #21 

The save method needs to be labelled as sync. Be on the look out for hf2.

**Comment by Drathonix** [comment]
I'll close this for now. If you haven't already update to hf2. If you experience any crashes at the end of chunk pregen, reopen this issue with the crash report.
