### ISSUE TITLE
CC:T is not compatible with Load My Chunks for 1.21.1

### ISSUE THREAD

**Issue by vico93** [Drathonix/LoadMyChunks#23]
**Mod Version**
LoadMyChunks-1.0.6-pre+1.21.1

**What were you doing before the crash happened?**
Basically I've updated a couple of mods, including loadmychunks and CC:T [1.113.0](https://github.com/cc-tweaked/CC-Tweaked/releases/tag/v1.21.1-1.113.0) and after that every time i try to access the new world menu the game crash.

**Provide Logs here:**
https://gist.github.com/vico93/b24455198cf8bf4a9b39f89a3e1a65d6

**Comment by Drathonix** [comment]
Of course he released it 2 hours ago, only 6 hours after me. All code related to CCT in load my chunks 1.21.1-pre is disabled at the moment

Do not use 1.21.1 LMC with CCT yet, I need to make sure the mod is compatible. Remain in 1.21 if you want stability. I'll look into compat right now.

(Also the CR leads me to believe its not a LMC problem. Look into the other mods you updated)

**Comment by vico93** [comment]
> (Also the CR leads me to believe its not a LMC problem. Look into the other mods you updated)

I actually asked for help in Fabric's Discord, and folks on there said it was a LMC issue. I think the crash specifically is caused by DataLoader forcing the loading of an invalid datapack (in the case, the .json data from LMC about upgrades that seems to be broken for the new CC:T).

**Comment by Drathonix** [comment]
> > (Also the CR leads me to believe its not a LMC problem. Look into the other mods you updated)
> 
> I actually asked for help in Fabric's Discord, and folks on there said it was a LMC issue. I think the crash specifically is caused by DataLoader forcing the loading of an invalid datapack (in the case, the .json data from LMC about upgrades that seems to be broken for the new CC:T).

```
java.lang.IllegalStateException: Failed to parse loadmychunks:computercraft/turtle_upgrade/yellow_chunk_loader.json from pack loadmychunks
	at net.minecraft.class_7655.method_45122(class_7655.java:251)
	at net.minecraft.class_7655$class_9158.method_56520(class_7655.java:96)
	at net.minecraft.class_7655.method_56514(class_7655.java:151)
	at net.minecraft.class_7655.method_45120(class_7655.java:164)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at net.minecraft.class_7655.method_45121(class_7655.java:164)
```
	
Found what you're referring to. These errors typically don't cause a crash, but as I said its not surprising given 1.21.1 LMC does not include CCT support. In future pre-CCT releases I'll exclude the CCT datapack entries so that this doesn't occur again.

**Comment by Drathonix** [comment]
@vico93 

The new mod version is not even uploaded to the maven yet, I'll do a check every day until it does. Until it does I can't update. I'll keep this issue opened for anyone entering the repo in this situation and if its significant enough that I can't wait I'll push a hotfix out excluding the datapack entries. The file on Cf is also marked alpha o that'd explain why its not on the maven yet.

As I said the fix is to downgrade mc versions until squiddev maven gets the version we need.

**Comment by Drathonix** [comment]
This problem is fixed (the CC:T maven just relocated for the third time XD)
