### ISSUE TITLE
[Feature] A way to consume x item every x time to load chunks

### ISSUE THREAD

**Issue by TeraNovell** [Drathonix/LoadMyChunks#26]
**What would you like added or changed?**
Chunk loading without any price I find too easy and tends to make people load everything they can on servers. If possible I would think of something like the [Personal Anchor](https://ftb.fandom.com/wiki/Personal_Anchor) from Railcraft. They always used up ender pearls to load chunks. This could be made configurable so that there are no problems with the previous behaviour. If nothing is configured, they run as before. Would something like this be possible? Thanks in advance ^^

**Comment by Drathonix** [comment]
I could definitely add this functionality. I'll look into it for next update.

**Comment by Drathonix** [comment]
Added in V-1.1.0

You'll need to enable it manually in the config file upon updating.
