### ISSUE TITLE
Fabric Server Crashed because of LoadMyChunks mod.

### ISSUE THREAD

**Issue by GuyWithBeer** [Drathonix/LoadMyChunks#4]
**Mod Version**
LoadMyChunks-LOADMYCHUNKSVER-MINECRAFTVER

**What were you doing before the crash happened?**
i downloaded the mods, place them in mod folder and started the server and gave error in load my chunk mod.

**Provide Logs here: (https://api.mclo.gs/1/raw/i6aCfSW) **

**Comment by Drathonix** [comment]
This is not your fault, its mine.

Problem is caused by line 
"NetworkManager.registerReceiver(NetworkManager.Side.S2C,LagReadingPacket.TYPE,LagReadingPacket.STREAM_CODEC,LagReadingPacket::handleClient);" in main class.

Needs to be moved to client side initialization. Will push an update soon.

**Comment by Drathonix** [comment]
Issue is present only in 1.20.6 and 1.21.

**Comment by Drathonix** [comment]
Hotfix files uploaded to Curse and Modrinth. Currently under review on curseforge.
