### ISSUE TITLE
1.0.3 Server crash

### ISSUE THREAD

**Issue by Phasertokill** [Drathonix/LoadMyChunks#6]
**Mod Version**
LoadMyChunks-LOADMYCHUNKSVER-MINECRAFTVER ver. 1.0.3

**What were you doing before the crash happened?**
I was trying to add the mod to server files but kept getting an error when launching server.

**Provide Logs here:**
https://mclo.gs/RDGNvrr

**Comment by Drathonix** [comment]
So I made an exact copy of your server based on the mods in the logs (minus the ones that Neo ignored) with NeoForge version 21.0.24, you're running 21.0.21

I was able to start my server successfully without encountering issues.

You are also missing Architectury, which will cause problems but not this one. I've never even seen this type of mixin error before.

I'll try to find out what went wrong for you but I have no guarantees I'll find the cause of the issue. What I recommend doing right now is updating all you mods and your NeoForge server to 21.0.24 , install architectury, and try booting then, given Neo is in beta its possible the older version has caused the conflict.

(EDIT: SEE SECOND COMMENT FIRST, IT MAY BE MORE RELEVANT)

**Comment by Drathonix** [comment]
Ah I might know the issue. You're running Java 22 when MC 1.21 and LMC are designed for Java 21, I recommend you downgrade your java version.

Adding this here for reference
https://forums.minecraftforge.net/topic/122864-resolved-game-crashing-caused-by-orgspongepoweredasmmixinthrowablesclassmetadatanotfoundexception-javalangsystem/

**Comment by Phasertokill** [comment]
I appreciate the quick response! Adding Architectury resolved the issue, but I followed your advice, downgraded to Java 21, and updated Neoforge. Thank you for the wonderful mod and support!

**Comment by Phasertokill** [comment]
Resolved! Thank you!
